version: "3.9"

services:
  pg_master:
    image: postgres:15
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command: >
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c listen_addresses=*
    volumes:
      - ./init/master_init.sql:/docker-entrypoint-initdb.d/01_master_init.sql
      - ./scripts:/scripts

  pg_replica:
    image: postgres:15
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    command: >
      -c max_logical_replication_workers=10
      -c max_worker_processes=30
    volumes:
      - ./init/replica_init.sql:/docker-entrypoint-initdb.d/01_replica_init.sql
      - ./scripts:/scripts